[[main]]
  identifier = "syllabus"
  name = "Syllabus"
  url = "docs"
  weight = 1

[[main]]
  identifier = "Course Work"
  name = "Weekly Work"
  url = "week"
  weight = 2

[[main]]
  identifier = "blog"
  name = "News"
  url = "blog"
  weight = 3
