logo = true
logoText = "HIST3814|DIGH3814"
logoType = "short" # long, short
description = "Fall 2025 Edition @Carleton U."

themeOptions = ["light", "dark"]

useFaviconGenerator = true # https://www.favicon-generator.org/

enableTocSwitch = true
enableLandingBackground = true
enableSearch = true
enableSearchHighlight = true
enableLangChange = false
enableDarkMode = true
enableBreadcrumb = false
enableBlogBreadcrumb = true
enableEditBtn = false
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = true

tocLevels = ["h2", "h3", "h4"]
paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

github = "https://github.com/roguehistory/Hist_Digh3814"


#whoami
enableWhoami = true
myname = "Prof. Scott Coleman"
email = "scottcoleman@cmail.carleton.ca"
whoami = "Instructor"
biImageUrl = "https://carleton.ca/history/cu-people/scott-coleman/"

# comment
enableComment = false
disqus_shortname = ""
commento = false
